######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 7 13:22:32 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . .
INCLUDEPATH += .
DEFINES += TEST
# Input
HEADERS += serialimu.h
SOURCES += serialimu.cc
