######################################################################
# Automatically generated by qmake (1.07a) Wed Jul 22 10:54:56 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += ../common
LIBS += -lcwiid
# Input
SOURCES += wii_remote.cc \
	../../../Structures/DriveVector.cc \
	../../../Communication/UDPSocket.cc


