######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 26 12:13:08 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..

# Input
HEADERS +=  ../bbcomm.h ../udpsocket.h bbclient.h
SOURCES += main.cc  ../bbcomm.cc ../udpsocket.cc bbclient.cpp
