######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 7 13:22:32 2009
######################################################################

TEMPLATE = app
TARGET = 
CONFIG += DEBUG
DEPENDPATH += . .
INCLUDEPATH += .
LIBS += -lusb
DEFINES += USE_USBIMU_MAIN USE_USB_IMU
# Input
HEADERS += imu.h
HEADERS += usbimu.h
SOURCES += imu.cc
