######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 19 21:59:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += client.cpp 
