######################################################################
# Automatically generated by qmake (1.07a) Wed Mar 31 14:16:52 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += tcpsocket.h stuttgartinterface.h
SOURCES += main.cc tcpsocket.cc
