######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 26 10:38:06 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cc
SOURCES += Time.cc
