######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 26 10:37:41 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cc
