######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 24 00:24:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tribotsv4l.h
SOURCES += tribotsv4l.cc
