######################################################################
# Automatically generated by qmake (1.07a) Tue May 10 15:52:48 2005
######################################################################

TEMPLATE = app
INCLUDEPATH     += . ../../../Libs/robotCtrLib/include /opt/local/include

LIBS    +=  -L../../../Libs/robotCtrLib -L../../../Libs/jpeg-6b/ -ljpeg
# Input
HEADERS += ../../components/ImageWidget.h
SOURCES += main.cc \
           ../../components/ImageWidget.cpp \
           ../../../ImageProcessing/Formation/ImageProducer.cc \
           ../../../ImageProcessing/Formation/MultiImageProducer.cc \
           ../../../ImageProcessing/Formation/Image.cc \
           ../../../ImageProcessing/Formation/RGBImage.cc \
           ../../../ImageProcessing/Formation/YUVImage.cc \
           ../../../Fundamental/ConfigReader.cc \
           ../../../ImageProcessing/PixelAnalysis/Image2WorldMapping.cc \
           ../../../ImageProcessing/PixelAnalysis/DirectionalCameraMapping.cc \
           ../../../ImageProcessing/PixelAnalysis/OmniCameraMapping.cc \
           ../../../Fundamental/Vec.cc \
           ../../../Fundamental/geometry3D.cc \
           ../../../Fundamental/Time.cc \
           ../../../Structures/TribotsException.cc \
           ../../../Fundamental/geometry.cc \
           ../../../Fundamental/Angle.cc \
           ../../../Fundamental/Frame2D.cc \
           ../../../Fundamental/Vec3D.cc \
           ../../../Structures/VisibleObject.cc \
           ../../../ImageProcessing/Formation/FileSource.cc \
           ../../../ImageProcessing/Formation/UYVYImage.cc \
           ../../../ImageProcessing/Formation/YUV411Image.cc \
           ../../../ImageProcessing/PixelAnalysis/ColorClassifier.cc \
           ../../../ImageProcessing/PixelAnalysis/YUVLookupTable.cc \
           ../../../ImageProcessing/Formation/ImageIO.cc \
           ../../../ImageProcessing/Formation/FileMonitor.cc \
           ../../../ImageProcessing/Formation/JPEGIO.cc \
           ../../../ImageProcessing/Formation/PPMIO.cc \
           ../../../ImageProcessing/Formation/ImageBuffer.cc \
           ../../../ImageProcessing/Formation/ImageConversion.cc \
           ../../../ImageProcessing/Formation/ImageSourceFactory.cc \
           ../../../ImageProcessing/ImageProcessingFactory.cc \
           ../../../Structures/Journal.cc \
           ../../../ImageProcessing/PixelAnalysis/RobotMask.cc \
           ../../../Structures/MessageBoard.cc \
           ../../../Structures/FieldGeometry.cc \
           ../../../Structures/DriveVector.cc \
           ../../../Structures/ObstacleLocation.cc \
           ../../../Structures/RobotProperties.cc \
           ../../../Structures/RobotData.cc \
           ../../../ImageProcessing/Formation/Painter.cc \
           ../../../ImageProcessing/ObjectAnalysis/ChainCoding.cc \
           ../../../ImageProcessing/ObjectAnalysis/Regions.cc \
           ../../../Fundamental/stringconvert.cc \
           ../../../ImageProcessing/ObjectAnalysis/ColorClasses.cc
