######################################################################
# Automatically generated by qmake (1.07a) Tue Apr 14 15:21:52 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .
LIBS += -lusb



# Input
HEADERS += kick.h
SOURCES += kick.c
