######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 7 13:22:32 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . .
INCLUDEPATH += .
LIBS += -lusb
DEFINES += TEST
# Input
HEADERS += imu.h
HEADERS += usbimu.h
SOURCES += imu.cc
