######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 7 16:02:00 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /usr/include/vtk-5.2/ .
LIBS += -lvtkRendering -lvtkHybrid
# Input
SOURCES += visualizer.cpp
SOURCES += udpsocket.cc
