######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 23 21:47:28 2010
######################################################################

TEMPLATE = app
TARGET = visionserver 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -ljpeg -lncurses -ln++ -lNFQ -lLA -lstdc++ 

### LIBPATH: non-standard library pathes (without initial -L)
LIBPATH += ../Libs/jpeg-6b ../Libs/n++/lib ../Libs/NFQ/lib ../Libs/LA/lib

### INCLUDEPATH: non-standard include pathes (without initial -I)
INCLUDEPATH += ../Libs/jpeg-6b ../Libs/n++/include ../Libs/NFQ/include ../Libs/LA/include

LIBS += -lAssiLib
LIBPATH += ../Libs/Alib/AssiLib
INCLUDEPATH += ../Libs/Alib/AssiLib
DEFINES += ASSIHTTP

LIBS += -ldc1394_control -lraw1394

# Input
HEADERS +=  ../ImageProcessing/Vision.h \
           ../Structures/TribotsException.h \
           ../Fundamental/ConfigReader.h \
           ../ImageProcessing/VisionType.h \
SOURCES += visionserver.cc \
           ../ImageProcessing/Vision.cc \
           ../Structures/TribotsException.cc \
           ../Fundamental/ConfigReader.cc \
           ../Structures/VisibleObject.cc \
           ../Fundamental/Time.cc \
           ../Fundamental/Vec.cc \
           ../Fundamental/Angle.cc \
           ../ImageProcessing/ObjectAnalysis/Regions.cc \
           ../ImageProcessing/ObjectAnalysis/ChainCoding.cc \
           ../ImageProcessing/Types/ScanLineImageProcessing.cc \
           ../Structures/Journal.cc \
           ../Audio/WavePlay.cc
SOURCES+=../Fundamental/Angle.cc 
SOURCES+=../Fundamental/ConfigReader.cc 
SOURCES+=../Fundamental/Frame2D.cc 
SOURCES+=../Fundamental/Joystick.cc 
SOURCES+=../Fundamental/PIDController.cc 
SOURCES+=../Fundamental/VSController.cc 
SOURCES+=../Fundamental/PiecewiseLinearFunction.cc 
SOURCES+=../Fundamental/POSIXThread.cc 
SOURCES+=../Fundamental/Time.cc 
SOURCES+=../Fundamental/Vec.cc 
SOURCES+=../Fundamental/Vec3D.cc 
SOURCES+=../Fundamental/binary_encoding.cc 
SOURCES+=../Fundamental/geometry.cc 
SOURCES+=../Fundamental/geometry3D.cc 
SOURCES+=../Fundamental/stringconvert.cc 
SOURCES+=../Fundamental/SmoothingFilter.cc 
SOURCES+=../Communication/UDPSocket.cc 
SOURCES+=../Fundamental/RemoteTune.cc 
SOURCES+=../Fundamental/BallLocationHysteresis.cc 
SOURCES+=../ImageProcessing/ImageProcessing.cc 
SOURCES+=../ImageProcessing/ImageProcessingFactory.cc 
SOURCES+=../ImageProcessing/Vision.cc 
SOURCES+=../ImageProcessing/VisionFactory.cc 
SOURCES+=../ImageProcessing/Calibration/CameraOptics.cc 
SOURCES+=../ImageProcessing/Formation/FileMonitor.cc 
SOURCES+=../ImageProcessing/Formation/FileSource.cc 
SOURCES+=../ImageProcessing/Formation/Image.cc 
SOURCES+=../ImageProcessing/Formation/ImageBuffer.cc 
SOURCES+=../ImageProcessing/Formation/ImageConversion.cc 
SOURCES+=../ImageProcessing/Formation/ImageIO.cc 
SOURCES+=../ImageProcessing/Formation/BufferedIO.cc 
SOURCES+=../ImageProcessing/Formation/ImageProducer.cc 
SOURCES+=../ImageProcessing/Formation/ImageSourceFactory.cc 
SOURCES+=../ImageProcessing/Formation/JPEGIO.cc 
SOURCES+=../ImageProcessing/Formation/MultiImageProducer.cc 
SOURCES+=../ImageProcessing/Formation/Painter.cc 
SOURCES+=../ImageProcessing/Formation/PPMIO.cc 
SOURCES+=../ImageProcessing/Formation/RGBImage.cc 
SOURCES+=../ImageProcessing/Formation/UYVYImage.cc 
SOURCES+=../ImageProcessing/Formation/YUVImage.cc 
SOURCES+=../ImageProcessing/Formation/YUV411Image.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/BallDetector.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/ChainCoding.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/ColorClasses.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/ContourObstacleDetector.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/FieldMapper.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/GoalDetector.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/LineDetector.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/LineScanning.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/LineFilter.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/Regions.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/ScanLines.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/SimpleCluster.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/SimpleObstacleDetector.cc 
SOURCES+=../ImageProcessing/PixelAnalysis/ColorClassifier.cc 
SOURCES+=../ImageProcessing/PixelAnalysis/Image2WorldMapping.cc 
SOURCES+=../ImageProcessing/PixelAnalysis/OmniCameraMapping.cc 
SOURCES+=../ImageProcessing/PixelAnalysis/DirectionalCameraMapping.cc 
SOURCES+=../ImageProcessing/PixelAnalysis/RobotMask.cc 
SOURCES+=../ImageProcessing/PixelAnalysis/YUVLookupTable.cc 
SOURCES+=../ImageProcessing/Types/FileVision.cc 
SOURCES+=../ImageProcessing/Types/VisionDummy.cc 
SOURCES+=../ImageProcessing/Types/GenericMultiSourceVision.cc 
SOURCES+=../ImageProcessing/Types/ScanLineImageProcessing.cc 
SOURCES+=../ImageProcessing/Types/DirectionalImageProcessing.cc 
SOURCES+=../ImageProcessing/Types/DribbleImageProcessing.cc 
SOURCES+=../Robot/CompassGrabbingThread.cc 
SOURCES+=../Robot/FileRobot.cc 
SOURCES+=../Robot/Robot.cc 
SOURCES+=../Robot/RobotDummy.cc 
SOURCES+=../Robot/RobotFactory.cc 
SOURCES+=../Structures/BallLocationReadWriter.cc 
SOURCES+=../Structures/DriveVector.cc 
SOURCES+=../Structures/DriveVectorReadWriter.cc 
SOURCES+=../Structures/FieldGeometry.cc 
SOURCES+=../Structures/GameState.cc 
SOURCES+=../Structures/GameStateReadWriter.cc 
SOURCES+=../Structures/GyroDataReadWriter.cc 
SOURCES+=../Structures/Journal.cc 
SOURCES+=../Structures/MessageBoard.cc 
SOURCES+=../Structures/MessageBoardReadWriter.cc 
SOURCES+=../Structures/ObstacleLocation.cc 
SOURCES+=../Structures/ObstacleLocationReadWriter.cc 
SOURCES+=../Structures/RobotData.cc 
SOURCES+=../Structures/RobotLocationReadWriter.cc 
SOURCES+=../Structures/RobotProperties.cc 
SOURCES+=../Structures/TacticsBoard.cc 
SOURCES+=../Structures/TacticsBoardDescription.cc 
SOURCES+=../Structures/TeammateLocation.cc 
SOURCES+=../Structures/TribotsException.cc 
SOURCES+=../Structures/VisibleObject.cc 
SOURCES+=../Structures/VisibleObjectReadWriter.cc 
SOURCES+=../Structures/default_exception_handler.cc 
SOURCES+=../WorldModel/WorldModel.cc 
SOURCES+=../WorldModel/WorldModelFactory.cc 
SOURCES+=../WorldModel/Ball/DynamicSlidingWindowBallFilter3D.cc 
SOURCES+=../WorldModel/Ball/MultiCameraBallFilter.cc 
SOURCES+=../WorldModel/Prediction/LocationShortTermMemory.cc 
SOURCES+=../WorldModel/Prediction/ObjectInteractionManager.cc 
SOURCES+=../WorldModel/Prediction/SingleStepHeuristicVelocityPredictor.cc 
SOURCES+=../WorldModel/Prediction/update_robot_location.cc 
SOURCES+=../WorldModel/Obstacles/EMAObstacleFilter.cc 
SOURCES+=../WorldModel/Obstacles/ObstacleContainer.cc 
SOURCES+=../WorldModel/Orga/GameStateManager.cc 
SOURCES+=../WorldModel/Orga/OdometryContainer.cc 
SOURCES+=../WorldModel/Orga/RefereeStateMachine.cc 
SOURCES+=../WorldModel/Orga/VisualContainer.cc 
SOURCES+=../WorldModel/SL/FieldLUT.cc 
SOURCES+=../WorldModel/SL/RobotPositionKalmanFilter.cc 
SOURCES+=../WorldModel/SL/RobotPositionPredictor.cc 
SOURCES+=../WorldModel/SL/SLStuckSensor.cc 
SOURCES+=../WorldModel/SL/SLVelocitySensor.cc 
SOURCES+=../WorldModel/SL/VisualPositionOptimiser.cc 
SOURCES+=../WorldModel/SL/TemporalDifferenceSL.cc 
SOURCES+=../WorldModel/Types/AddWriteWorldModel.cc 
SOURCES+=../WorldModel/Types/ErrorMinimiserWorldModel.cc 
SOURCES+=../WorldModel/Types/FileWorldModel.cc 
SOURCES+=../WorldModel/Types/WorldModelDummy.cc 
SOURCES+=../WorldModel/Types/WorldModelTypeBase.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/PolarObstacleCluster.cc 
SOURCES+=../ImageProcessing/ObjectAnalysis/PolarObstacleDetector.cc 
SOURCES+=../ImageProcessing/Calibration/centerRingOperation.cc 
SOURCES+=../ImageProcessing/Calibration/ImageArea.cc 
SOURCES+=../ImageProcessing/Calibration/ImageCenterSurveillance.cc 
SOURCES+=../Audio/WavePlay.cc 
SOURCES+=../ImageProcessing/Formation/PS3EyeImageSource.cc 

# Zusatzeinstellungen bei Benutzung der Kamera



SOURCES += \
../ImageProcessing/Formation/IIDC.cc \
../ImageProcessing/Formation/CamDriver.cc \
../tools/DistanceCalibration/DistanceCalibration.cc \
../tools/DistanceCalibration/ImageProcessingDistanceCalibration.cc 
