######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 23 21:47:28 2010
######################################################################

TEMPLATE = app
CONFIG -=qt
TARGET = worldmodel 
DEPENDPATH += .
INCLUDEPATH += .
OBJECTS_DIR=OBJECTS

LIBS +=  -lLA -lstdc++ 

### LIBPATH: non-standard library pathes (without initial -L)
LIBPATH +=  Libs/LA/lib

### INCLUDEPATH: non-standard include pathes (without initial -I)
INCLUDEPATH +=   Libs/LA/include

CONFIG -=qt

# Input
HEADERS += Structures/TribotsException.h \
           Fundamental/ConfigReader.h 


SOURCES = worldmodel.cc
SOURCES += Structures/TribotsException.cc \
           Fundamental/ConfigReader.cc \
           Fundamental/Time.cc \
	   Fundamental/Angle.cc \
	   Fundamental/Frame2D.cc \
	   Fundamental/Vec.cc \
	   Fundamental/Vec3D.cc \
	   Fundamental/binary_encoding.cc \
	   Fundamental/geometry.cc \
	   Fundamental/geometry3D.cc \
	   Fundamental/stringconvert.cc \
	   Fundamental/SmoothingFilter.cc \
	   Structures/BallLocationReadWriter.cc \
	   Structures/DriveVector.cc \
	   Structures/DriveVectorReadWriter.cc \
	   Structures/FieldGeometry.cc \
	   Structures/GameState.cc \
	   Structures/GameStateReadWriter.cc \
	   Structures/GyroDataReadWriter.cc \
	   Structures/Journal.cc \
	   Structures/MessageBoard.cc \
	   Structures/MessageBoardReadWriter.cc \
	   Structures/ObstacleLocation.cc \
	   Structures/ObstacleLocationReadWriter.cc \
	   Structures/RobotData.cc \
	   Structures/RobotLocationReadWriter.cc \
	   Structures/RobotProperties.cc \
	   Structures/TacticsBoard.cc \
	   Structures/TacticsBoardDescription.cc \
	   Structures/TeammateLocation.cc \
	   Structures/VisibleObject.cc \
	   Structures/VisibleObjectReadWriter.cc \
	   Structures/default_exception_handler.cc \
WorldModel/WorldModel.cc \
WorldModel/WorldModelFactory.cc \
WorldModel/Ball/DynamicSlidingWindowBallFilter3D.cc \
WorldModel/Ball/MultiCameraBallFilter.cc \
WorldModel/Prediction/LocationShortTermMemory.cc \
WorldModel/Prediction/ObjectInteractionManager.cc \
WorldModel/Prediction/SingleStepHeuristicVelocityPredictor.cc \
WorldModel/Prediction/update_robot_location.cc \
WorldModel/Obstacles/EMAObstacleFilter.cc \
WorldModel/Obstacles/ObstacleContainer.cc \
WorldModel/Orga/GameStateManager.cc \
WorldModel/Orga/OdometryContainer.cc \
WorldModel/Orga/RefereeStateMachine.cc \
WorldModel/Orga/VisualContainer.cc \
WorldModel/SL/FieldLUT.cc \
WorldModel/SL/RobotPositionKalmanFilter.cc \
WorldModel/SL/RobotPositionPredictor.cc \
WorldModel/SL/SLStuckSensor.cc \
WorldModel/SL/SLVelocitySensor.cc \
WorldModel/SL/VisualPositionOptimiser.cc \
WorldModel/SL/TemporalDifferenceSL.cc \
WorldModel/Types/AddWriteWorldModel.cc \
WorldModel/Types/ErrorMinimiserWorldModel.cc \
WorldModel/Types/FileWorldModel.cc \
WorldModel/Types/WorldModelDummy.cc \
WorldModel/Types/WorldModelTypeBase.cc 
