######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 23 21:47:28 2010
######################################################################

TEMPLATE = app
TARGET = visionserver 
DEPENDPATH += .
INCLUDEPATH += .
#OBJECTS_DIR=OBJECTS
LIBS += -ljpeg -lncurses -ln++ -lNFQ -lLA -lstdc++ 

### LIBPATH: non-standard library pathes (without initial -L)
LIBPATH += Libs/jpeg-6b Libs/n++/lib Libs/NFQ/lib Libs/LA/lib

### INCLUDEPATH: non-standard include pathes (without initial -I)
INCLUDEPATH += Libs/jpeg-6b Libs/n++/include Libs/NFQ/include Libs/LA/include


LIBS += -ldc1394_control -lraw1394

# Input
HEADERS +=  ImageProcessing/Vision.h \
           Structures/TribotsException.h \
           Fundamental/ConfigReader.h \
           ImageProcessing/VisionType.h \


SOURCES = visionserver.cc
SOURCES += ImageProcessing/Vision.cc \
           Structures/TribotsException.cc \
           Fundamental/ConfigReader.cc \
           Fundamental/Time.cc \
           ImageProcessing/Types/ScanLineImageProcessing.cc \
	   Fundamental/Angle.cc \
	   Fundamental/Frame2D.cc \
	   Fundamental/Joystick.cc \
	   Fundamental/PIDController.cc \
	   Fundamental/VSController.cc \
	   Fundamental/PiecewiseLinearFunction.cc \
	   Fundamental/POSIXThread.cc \
	   Fundamental/Vec.cc \
	   Fundamental/Vec3D.cc \
	   Fundamental/binary_encoding.cc \
	   Fundamental/geometry.cc \
	   Fundamental/geometry3D.cc \
	   Fundamental/stringconvert.cc \
	   Fundamental/SmoothingFilter.cc \
	   Communication/UDPSocket.cc \
	   Fundamental/RemoteTune.cc \
	   ImageProcessing/ImageProcessing.cc \
	   ImageProcessing/ImageProcessingFactory.cc \
	   ImageProcessing/VisionFactory.cc \
	   ImageProcessing/Calibration/CameraOptics.cc \
	   ImageProcessing/Formation/FileMonitor.cc \
	   ImageProcessing/Formation/FileSource.cc \
	   ImageProcessing/Formation/Image.cc \
	   ImageProcessing/Formation/ImageBuffer.cc \
	   ImageProcessing/Formation/ImageConversion.cc \
	   ImageProcessing/Formation/ImageIO.cc \
	   ImageProcessing/Formation/BufferedIO.cc \
	   ImageProcessing/Formation/ImageProducer.cc \
	   ImageProcessing/Formation/ImageSourceFactory.cc \
	   ImageProcessing/Formation/JPEGIO.cc \
	   ImageProcessing/Formation/MultiImageProducer.cc \
	   ImageProcessing/Formation/Painter.cc \
	   ImageProcessing/Formation/PPMIO.cc \
	   ImageProcessing/Formation/RGBImage.cc \
	   ImageProcessing/Formation/UYVYImage.cc \
	   ImageProcessing/Formation/YUVImage.cc \
	   ImageProcessing/Formation/YUV411Image.cc \
	   ImageProcessing/ObjectAnalysis/BallDetector.cc \
	   ImageProcessing/ObjectAnalysis/ChainCoding.cc \
	   ImageProcessing/ObjectAnalysis/ColorClasses.cc \
	   ImageProcessing/ObjectAnalysis/ContourObstacleDetector.cc \
	   ImageProcessing/ObjectAnalysis/FieldMapper.cc \
	   ImageProcessing/ObjectAnalysis/LineDetector.cc \
	   ImageProcessing/ObjectAnalysis/LineScanning.cc \
	   ImageProcessing/ObjectAnalysis/LineFilter.cc \
	   ImageProcessing/ObjectAnalysis/Regions.cc \
	   ImageProcessing/ObjectAnalysis/ScanLines.cc \
	   ImageProcessing/ObjectAnalysis/SimpleCluster.cc \
	   ImageProcessing/ObjectAnalysis/SimpleObstacleDetector.cc \
	   ImageProcessing/PixelAnalysis/ColorClassifier.cc \
	   ImageProcessing/PixelAnalysis/Image2WorldMapping.cc \
	   ImageProcessing/PixelAnalysis/OmniCameraMapping.cc \
	   ImageProcessing/PixelAnalysis/DirectionalCameraMapping.cc \
	   ImageProcessing/PixelAnalysis/RobotMask.cc \
	   ImageProcessing/PixelAnalysis/YUVLookupTable.cc \
	   ImageProcessing/Types/FileVision.cc \
	   ImageProcessing/Types/VisionDummy.cc \
	   ImageProcessing/Types/GenericMultiSourceVision.cc \
	   Structures/BallLocationReadWriter.cc \
	   Structures/DriveVector.cc \
	   Structures/DriveVectorReadWriter.cc \
	   Structures/FieldGeometry.cc \
	   Structures/GameState.cc \
	   Structures/GameStateReadWriter.cc \
	   Structures/GyroDataReadWriter.cc \
	   Structures/Journal.cc \
	   Structures/ObstacleLocation.cc \
	   Structures/ObstacleLocationReadWriter.cc \
	   Structures/RobotData.cc \
	   Structures/RobotLocationReadWriter.cc \
	   Structures/RobotProperties.cc \
	   Structures/TacticsBoard.cc \
	   Structures/TacticsBoardDescription.cc \
	   Structures/TeammateLocation.cc \
	   Structures/VisibleObject.cc \
	   Structures/VisibleObjectReadWriter.cc \
	   Structures/default_exception_handler.cc \
	   ImageProcessing/ObjectAnalysis/PolarObstacleCluster.cc \
	   ImageProcessing/ObjectAnalysis/PolarObstacleDetector.cc \
	   ImageProcessing/Calibration/centerRingOperation.cc \
	   ImageProcessing/Calibration/ImageArea.cc \
	   ImageProcessing/Calibration/ImageCenterSurveillance.cc \
	   Audio/WavePlay.cc \
	   ImageProcessing/Formation/PS3EyeImageSource.cc 


SOURCES += \
ImageProcessing/Formation/IIDC.cc \
ImageProcessing/Formation/CamDriver.cc \
tools/DistanceCalibration/DistanceCalibration.cc \
tools/DistanceCalibration/ImageProcessingDistanceCalibration.cc 
